
version: '3.8'

services:
  neo-rent-app:
    build: .
    container_name: neo-rent-smart-suite
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    volumes:
      # Pour utiliser vos propres certificats SSL (optionnel)
      # - ./ssl:/etc/nginx/ssl:ro
      # Pour personnaliser la configuration nginx (optionnel)
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - neo-rent-network

networks:
  neo-rent-network:
    driver: bridge
